## Preprocessing

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [2]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
#
new_application_df = application_df.drop(columns=['EIN','NAME'],axis=1)
new_application_df.head()

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [3]:
new_application_df.nunique()

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [4]:
# Determine the number of unique values in each column.
#
new_application_df['APPLICATION_TYPE']

0        T10
1         T3
2         T5
3         T3
4         T3
        ...
34294     T4
34295     T4
34296     T3
34297     T5
34298     T3
Name: APPLICATION_TYPE, Length: 34299, dtype: object

In [5]:
# Look at APPLICATION_TYPE value counts for binning
#
new_application_df['APPLICATION_TYPE'].value_counts()

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [36]:
new_application_df[['INCOME_AMT','ASK_AMT']]

          INCOME_AMT   ASK_AMT
0                  0      5000
1             1-9999    108590
2                  0      5000
3        10000-24999      6692
4      100000-499999    142590
...              ...       ...
34294              0      5000
34295              0      5000
34296              0      5000
34297              0      5000
34298          1M-5M  36500179

[34299 rows x 2 columns]

import numpy as np
from google.colab import autoviz
df_7463103357504356993 = autoviz.get_df('df_7463103357504356993')

def value_plot(df, y, sort_ascending=False, figsize=(2, 1)):
  from matplotlib import pyplot as plt
  if sort_ascending:
    df = df.sort_values(y).reset_index(drop=True)
  _, ax = plt.subplots(figsize=figsize)
  df[y].plot(kind='line')
  plt.title(y)
  ax.spines[['top', 'right',]].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = value_plot(df_7463103357504356993, *['ASK_AMT'], **{})
chart

import numpy as np
from google.colab import autoviz
df_5494615689550647319 = autoviz.get_df('df_5494615689550647319')

def histogram(df, colname, num_bins=20, figsize=(2, 1)):
  from matplotlib import pyplot as plt
  _, ax = plt.subplots(figsize=figsize)
  plt.hist(df[colname], bins=num_bins, histtype='stepfilled')
  plt.ylabel('count')
  plt.title(colname)
  ax.spines[['top', 'right',]].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = histogram(df_5494615689550647319, *['ASK_AMT'], **{})
chart

ERROR:root:Did not find quickchart key chart-bcf83842-5bce-4590-af76-e00b7cfb9825 in chart cache

In [6]:
application_types_list = new_application_df['APPLICATION_TYPE'].value_counts()
application_types_list[1]
# application_types_to_replace=[]
# application_types_to_replace =
# for i in range(lenght(application_types_list)):
#   if application_types_list[i] <500:

1542

In [7]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
#  Threshold set to 500

application_types_to_replace = application_types_list.loc[lambda x: x<500].index

# Replace in dataframe
for app in application_types_to_replace:
    new_application_df['APPLICATION_TYPE'] = new_application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
new_application_df['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: APPLICATION_TYPE, dtype: int64

In [8]:
classification_to_replace = new_application_df['CLASSIFICATION'].value_counts()
classification_to_replace

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [9]:
# Look at CLASSIFICATION value counts for binning
#  YOUR CODE GOES HERE

In [10]:
# You may find it helpful to look at CLASSIFICATION value counts >1
#  YOUR CODE GOES HERE

In [11]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
#  Threshold = 1000
classifications_to_replace = classification_to_replace.loc[lambda x: x<1000].index
# Replace in dataframe
for cls in classifications_to_replace:
    new_application_df['CLASSIFICATION'] = new_application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure binning was successful
new_application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: CLASSIFICATION, dtype: int64

In [12]:
# Convert categorical data to numeric with `pd.get_dummies`
#  YOUR CODE GOES HERE

cat_new_application_df = pd.get_dummies(new_application_df)
cat_new_application_df.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,1,108590,1,0,0,0,1,0,0,0,...,1,0,0,0,0,0,0,0,1,0
2,1,5000,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
3,1,6692,1,0,0,0,1,0,0,0,...,0,1,0,0,0,0,0,0,1,0
4,1,142590,1,0,0,0,1,0,0,0,...,0,0,1,0,0,0,0,0,1,0

In [13]:
# Split our preprocessed data into our features and target arrays
y = cat_new_application_df['IS_SUCCESSFUL']

X = cat_new_application_df.drop(['IS_SUCCESSFUL'],axis=1)

# Split the preprocessed data into a training and testing dataset

X_train, X_test, y_train, y_test = train_test_split (X,y, random_state = 69)
#  YOUR CODE GOES HERE

In [14]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [44]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
#

nn = tf.keras.models.Sequential()

# First hidden layer
# Add our first Dense layer, including the input layer
nn.add(tf.keras.layers.Dense(units=64, activation="relu", input_dim=43))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=4, activation="relu"))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn.summary()

Model: "sequential_6"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_16 (Dense)            (None, 64)                2816

 dense_17 (Dense)            (None, 4)                 260

 dense_18 (Dense)            (None, 1)                 5

=================================================================
Total params: 3,081
Trainable params: 3,081
Non-trainable params: 0
_________________________________________________________________

In [45]:
# Compile the model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [46]:
# Train the model
fit_model = nn.fit(X_train_scaled, y_train, epochs=100)

Epoch 1/100
804/804 [==============================] - 3s 2ms/step - loss: 0.5903 - accuracy: 0.6902
Epoch 2/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5596 - accuracy: 0.7247
Epoch 3/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5556 - accuracy: 0.7273
Epoch 4/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5541 - accuracy: 0.7282
Epoch 5/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5534 - accuracy: 0.7289
Epoch 6/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5516 - accuracy: 0.7296
Epoch 7/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5514 - accuracy: 0.7290
Epoch 8/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5508 - accuracy: 0.7291
Epoch 9/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5501 - accuracy: 0.7294
Epoch 10/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5500 - accuracy: 0.7303
Epoch 11/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5500 - accuracy: 0.7310
Epoch 12/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5495 - accuracy: 0.7306
Epoch 13/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5490 - accuracy: 0.7313
Epoch 14/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5486 - accuracy: 0.7316
Epoch 15/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5484 - accuracy: 0.7318
Epoch 16/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5485 - accuracy: 0.7311
Epoch 17/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5478 - accuracy: 0.7307
Epoch 18/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5474 - accuracy: 0.7318
Epoch 19/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5478 - accuracy: 0.7312
Epoch 20/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5469 - accuracy: 0.7322
Epoch 21/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5468 - accuracy: 0.7320
Epoch 22/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5467 - accuracy: 0.7334
Epoch 23/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5467 - accuracy: 0.7328
Epoch 24/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5463 - accuracy: 0.7318
Epoch 25/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5461 - accuracy: 0.7314
Epoch 26/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5460 - accuracy: 0.7324
Epoch 27/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5456 - accuracy: 0.7328
Epoch 28/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5455 - accuracy: 0.7329
Epoch 29/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5456 - accuracy: 0.7329
Epoch 30/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5458 - accuracy: 0.7336
Epoch 31/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5450 - accuracy: 0.7328
Epoch 32/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5454 - accuracy: 0.7336
Epoch 33/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5455 - accuracy: 0.7333
Epoch 34/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5451 - accuracy: 0.7336
Epoch 35/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5451 - accuracy: 0.7336
Epoch 36/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5448 - accuracy: 0.7340
Epoch 37/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5447 - accuracy: 0.7336
Epoch 38/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5445 - accuracy: 0.7340
Epoch 39/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5444 - accuracy: 0.7341
Epoch 40/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5444 - accuracy: 0.7337
Epoch 41/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5442 - accuracy: 0.7331
Epoch 42/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5446 - accuracy: 0.7337
Epoch 43/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5441 - accuracy: 0.7346
Epoch 44/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5442 - accuracy: 0.7332
Epoch 45/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5441 - accuracy: 0.7342
Epoch 46/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5439 - accuracy: 0.7329
Epoch 47/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5436 - accuracy: 0.7340
Epoch 48/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5434 - accuracy: 0.7348
Epoch 49/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5442 - accuracy: 0.7347
Epoch 50/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5438 - accuracy: 0.7342
Epoch 51/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5433 - accuracy: 0.7346
Epoch 52/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5436 - accuracy: 0.7343
Epoch 53/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5434 - accuracy: 0.7345
Epoch 54/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5435 - accuracy: 0.7349
Epoch 55/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5434 - accuracy: 0.7354
Epoch 56/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5429 - accuracy: 0.7350
Epoch 57/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5429 - accuracy: 0.7339
Epoch 58/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5428 - accuracy: 0.7341
Epoch 59/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5428 - accuracy: 0.7354
Epoch 60/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5431 - accuracy: 0.7346
Epoch 61/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5428 - accuracy: 0.7353
Epoch 62/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5434 - accuracy: 0.7334
Epoch 63/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5425 - accuracy: 0.7348
Epoch 64/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5427 - accuracy: 0.7345
Epoch 65/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5425 - accuracy: 0.7353
Epoch 66/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5426 - accuracy: 0.7353
Epoch 67/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5424 - accuracy: 0.7347
Epoch 68/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5425 - accuracy: 0.7349
Epoch 69/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5426 - accuracy: 0.7340
Epoch 70/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5422 - accuracy: 0.7350
Epoch 71/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5427 - accuracy: 0.7348
Epoch 72/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5424 - accuracy: 0.7342
Epoch 73/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5421 - accuracy: 0.7360
Epoch 74/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5425 - accuracy: 0.7354
Epoch 75/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5425 - accuracy: 0.7346
Epoch 76/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5424 - accuracy: 0.7339
Epoch 77/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5421 - accuracy: 0.7349
Epoch 78/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5420 - accuracy: 0.7356
Epoch 79/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5422 - accuracy: 0.7353
Epoch 80/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5418 - accuracy: 0.7364
Epoch 81/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5416 - accuracy: 0.7364
Epoch 82/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5419 - accuracy: 0.7355
Epoch 83/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5417 - accuracy: 0.7356
Epoch 84/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5414 - accuracy: 0.7357
Epoch 85/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5411 - accuracy: 0.7362
Epoch 86/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5421 - accuracy: 0.7345
Epoch 87/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5418 - accuracy: 0.7349
Epoch 88/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5415 - accuracy: 0.7350
Epoch 89/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5416 - accuracy: 0.7356
Epoch 90/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5413 - accuracy: 0.7353
Epoch 91/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5418 - accuracy: 0.7363
Epoch 92/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5414 - accuracy: 0.7353
Epoch 93/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5417 - accuracy: 0.7351
Epoch 94/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5412 - accuracy: 0.7361
Epoch 95/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5414 - accuracy: 0.7360
Epoch 96/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5411 - accuracy: 0.7352
Epoch 97/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5410 - accuracy: 0.7364
Epoch 98/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5410 - accuracy: 0.7351
Epoch 99/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5410 - accuracy: 0.7360
Epoch 100/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5412 - accuracy: 0.7355

In [47]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 1s - loss: 0.5504 - accuracy: 0.7318 - 504ms/epoch - 2ms/step
Loss: 0.5503813624382019, Accuracy: 0.7317784428596497

In [48]:
# Export our model to HDF5 file
#  YOUR CODE GOES HERE
nn.save('chanllenge21L2U130U215.h5')